package com.aa.mss.config;

import static com.google.common.base.Predicates.or;
import static springfox.documentation.builders.PathSelectors.regex;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import com.google.common.base.Predicate;

import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
@ComponentScan(basePackages = "com.aa.mss.fitrsservices")
public class SwaggerConfig {

	private Log logger = LogFactory.getLog(SwaggerConfig.class);

	@Bean
	public Docket apiDocket() {
		logger.debug("Initializing Swagger Docket bean");
		return new Docket(DocumentationType.SWAGGER_2).groupName("business-api").apiInfo(apiInfo()).select()
				.paths(paths()).build();
	}

	private ApiInfo apiInfo() {
		logger.debug("Returning Swagger ApiInfo object");
		return new ApiInfoBuilder().title("FITRS Service API")
				.description(
						"FITRS Service endpoints helps in managing financial system errors. These endpoints can be used to read various error and warning messages generated by other financial applications.")
				.termsOfServiceUrl("https://www.aa.com/homePage.do")
				.licenseUrl("https://www.aa.com/homePage.do/LICENSE").version("2.0").build();
	}

	private Predicate<String> paths() {
		logger.debug("Setting swagger api paths");
		return or(regex("/hello*.*"), regex("/.*"));

	}
}
